import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Navigate, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { CircleMarker, MapContainer, Polyline, Popup, TileLayer } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import './styles.css';

const api = async (path, options = {}) => {
  const response = await fetch(path, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options, body: options.body && JSON.stringify(options.body) });
  const json = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(json.error || 'Something went wrong.');
  return json;
};
const fmt = value => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const title = value => value.replaceAll('-', ' ').replace(/\b\w/g, char => char.toUpperCase());

function App() {
  const [user, setUser] = useState(undefined), [notice, setNotice] = useState(null);
  useEffect(() => { api('/api/me').then(({ user }) => setUser(user)).catch(() => setUser(null)); }, []);
  if (user === undefined) return <div className="loading">Loading FoodConnect…</div>;
  return <Shell user={user} setUser={setUser} notice={notice} setNotice={setNotice}/>;
}
function Shell({ user, setUser, notice, setNotice }) {
  const navigate = useNavigate();
  const logout = async () => { await api('/api/auth/logout', { method: 'POST' }); setUser(null); navigate('/'); };
  return <><header><Link to="/" className="brand">Food<span>Connect</span></Link><nav><NavLink to="/about">About</NavLink><NavLink to="/mission">Mission</NavLink><NavLink to="/contact">Contact</NavLink>{user ? <><Link className="avatar" to={`/${user.role}/dashboard`}>{user.firstName[0]}</Link><button className="link-btn" onClick={logout}>Logout</button></> : <><NavLink to="/login">Log in</NavLink><NavLink className="primary small" to="/signup">Sign up</NavLink></>}</nav></header>{notice && <div className={`notice ${notice.type || 'success'}`} onClick={() => setNotice(null)}>{notice.text}</div>}<Routes>
    <Route path="/" element={<Home/>}/><Route path="/about" element={<InfoPage title="About FoodConnect"><p>We redirect surplus edible food from restaurants, caterers and households to people who need it most.</p><p>Our donor, admin and collection-agent network makes every pickup traceable and practical.</p></InfoPage>}/><Route path="/mission" element={<InfoPage title="Our mission"><p>Reduce food waste, support local communities, and make nutritious food more accessible.</p></InfoPage>}/><Route path="/contact" element={<InfoPage title="Contact"><p>For help or feedback, contact the FoodConnect team through your local coordinator.</p></InfoPage>}/>
    <Route path="/login" element={user ? <RoleRedirect user={user}/> : <Login setUser={setUser}/>}/><Route path="/signup" element={user ? <RoleRedirect user={user}/> : <Signup setNotice={setNotice}/>}/><Route path="/verify" element={<Verify setUser={setUser}/>}/><Route path="/forgot" element={<Forgot/>}/><Route path="/reset" element={<Reset/>}/>
    <Route path="/:role/*" element={user ? <Protected user={user} setUser={setUser} setNotice={setNotice}/> : <Navigate to="/login" replace/>}/><Route path="*" element={<Navigate to="/" replace/>}/>
  </Routes><Faq user={user}/></>;
}
function Home(){ return <main className="home"><section className="hero"><div><p className="eyebrow">TURNING SURPLUS INTO SUPPORT</p><h1>Good food deserves a second destination.</h1><p>FoodConnect coordinates donors, admins and pickup agents in one clear workflow.</p><Link className="primary" to="/signup">Join FoodConnect</Link></div><img src="/assets/images/img-2.jpg" alt="Food donation"/></section><section className="steps"><div><b>1</b><h3>Donate</h3><p>Share the food and pickup details.</p></div><div><b>2</b><h3>Coordinate</h3><p>Admins review and assign a collector.</p></div><div><b>3</b><h3>Collect</h3><p>Agents complete the pickup.</p></div></section></main> }
function InfoPage({title: heading, children}) { return <main className="content"><p className="eyebrow">FOODCONNECT</p><h1>{heading}</h1>{children}</main> }
function FormShell({title: heading, children}) { return <main className="auth"><section><p className="eyebrow">FOODCONNECT</p><h1>{heading}</h1>{children}</section></main> }
function useForm(initial={}) { const [values,setValues]=useState(initial); const change=e=>setValues(v=>({...v,[e.target.name]:e.target.value})); return [values,change]; }
function Login({setUser}) { const [v,change]=useForm(); const [error,setError]=useState(''); const navigate=useNavigate(); const submit=async e=>{e.preventDefault();try{const data=await api('/api/auth/login',{method:'POST',body:v});setUser(data.user);navigate(`/${data.user.role}/dashboard`)}catch(err){setError(err.message)}}; return <FormShell title="Welcome back"><form onSubmit={submit}><Field label="Email" name="email" type="email" onChange={change}/><Field label="Password" name="password" type="password" onChange={change}/><Error text={error}/><button className="primary">Log in</button><p><Link to="/forgot">Forgot password?</Link> · <Link to="/signup">Create an account</Link></p></form></FormShell> }
function Signup({setNotice}) { const [v,change]=useForm({role:'donor'});const [error,setError]=useState('');const nav=useNavigate();const submit=async e=>{e.preventDefault();try{const r=await api('/api/auth/signup',{method:'POST',body:v});setNotice({text:r.message});nav('/verify',{state:{email:r.email}})}catch(err){setError(err.message)}};return <FormShell title="Create your account"><form onSubmit={submit}><div className="split"><Field label="First name" name="firstName" onChange={change}/><Field label="Last name" name="lastName" onChange={change}/></div><Field label="Email" type="email" name="email" onChange={change}/><div className="split"><Field label="Password" type="password" name="password1" onChange={change}/><Field label="Confirm password" type="password" name="password2" onChange={change}/></div><label>Role<select name="role" value={v.role} onChange={change}><option value="donor">Food donor</option><option value="agent">Collection agent</option><option value="admin">Administrator</option></select></label><Error text={error}/><button className="primary">Send verification code</button></form></FormShell> }
function Verify({setUser}){const[v,change]=useForm();const[error,setError]=useState('');const nav=useNavigate();const submit=async e=>{e.preventDefault();try{const r=await api('/api/auth/verify',{method:'POST',body:v});setUser(r.user);nav(`/${r.user.role}/dashboard`)}catch(err){setError(err.message)}};return <FormShell title="Verify your email"><p>Enter the six-digit code sent to your email.</p><form onSubmit={submit}><Field label="Verification code" name="otp" onChange={change}/><Error text={error}/><button className="primary">Verify account</button></form></FormShell>}
function Forgot(){const[v,change]=useForm();const[message,setMessage]=useState('');const submit=async e=>{e.preventDefault();try{setMessage((await api('/api/auth/forgot',{method:'POST',body:v})).message)}catch(err){setMessage(err.message)}};return <FormShell title="Reset your password"><form onSubmit={submit}><Field label="Email" type="email" name="email" onChange={change}/><p>{message}</p><button className="primary">Send reset code</button>{message && <Link to="/reset">I have a code</Link>}</form></FormShell>}
function Reset(){const[v,change]=useForm();const[message,setMessage]=useState('');const submit=async e=>{e.preventDefault();try{setMessage((await api('/api/auth/reset',{method:'POST',body:v})).message)}catch(err){setMessage(err.message)}};return <FormShell title="Choose a new password"><form onSubmit={submit}><Field label="Email" type="email" name="email" onChange={change}/><Field label="Reset code" name="otp" onChange={change}/><div className="split"><Field label="New password" type="password" name="password1" onChange={change}/><Field label="Confirm password" type="password" name="password2" onChange={change}/></div><p>{message}</p><button className="primary">Update password</button></form></FormShell>}
function Field({label,...props}){return <label>{label}<input required {...props}/></label>} function Error({text}){return text && <p className="error">{text}</p>}
function RoleRedirect({user}){return <Navigate to={`/${user.role}/dashboard`} replace/>}
function Protected({user,setUser,setNotice}) { const {role}=useParams(); if(role!==user.role)return <RoleRedirect user={user}/>;return <div className="portal"><Sidebar user={user}/><main className="workspace"><Routes><Route path="dashboard" element={<Dashboard user={user}/>}/><Route path="donate" element={<Donate setNotice={setNotice}/>}/><Route path="donations/:bucket" element={<Donations user={user} setNotice={setNotice}/>}/><Route path="donation/:id" element={<DonationDetail user={user} setNotice={setNotice}/>}/><Route path="agents" element={<Agents/>}/><Route path="profile" element={<Profile user={user} setUser={setUser} setNotice={setNotice}/>}/><Route path="route-planner" element={<RoutePlanner/>}/><Route path="*" element={<RoleRedirect user={user}/>}/></Routes></main></div> }
function Sidebar({user}){const links=user.role==='admin'?[['dashboard','Dashboard'],['donations/pending','Active donations'],['donations/previous','History'],['agents','Agents'],['profile','Profile']]:user.role==='donor'?[['dashboard','Dashboard'],['donate','Donate food'],['donations/pending','Pending donations'],['donations/previous','Donation history'],['profile','Profile']]:[['dashboard','Dashboard'],['donations/pending','Pending collections'],['donations/previous','Collection history'],['route-planner','Route planner'],['profile','Profile']];return <aside><p>WELCOME, {user.firstName.toUpperCase()}</p>{links.map(([to,label])=><NavLink key={to} to={`/${user.role}/${to}`}>{label}</NavLink>)}</aside>}
function Dashboard({user}){const[data,setData]=useState();useEffect(()=>{api('/api/dashboard').then(setData)},[]);if(!data)return <Loading/>;const labels=user.role==='agent'?{assigned:'Pending collections',collected:'Collected'}:{pending:'Pending',accepted:'Accepted',assigned:'Assigned',collected:'Collected'};return <Page title="Dashboard"><div className="intro"><p className="eyebrow">OVERVIEW</p><h1>Hello, {user.firstName}.</h1><p>Here’s the live status of your FoodConnect work.</p></div><div className="cards">{Object.entries(labels).map(([key,label])=><article key={key}><p>{label}</p><strong>{data.counts[key]||0}</strong></article>)}{data.users&&Object.entries(data.users).map(([key,value])=><article key={key}><p>{title(key)}</p><strong>{value}</strong></article>)}</div></Page>}
function Donate({setNotice}){const[v,change]=useForm();const nav=useNavigate();const[error,setError]=useState('');const submit=async e=>{e.preventDefault();try{await api('/api/donations',{method:'POST',body:v});setNotice({text:'Donation request sent successfully.'});nav('/donor/donations/pending')}catch(err){setError(err.message)}};return <Page title="Donate food"><p className="help-text">Verified details, a valid Indian mobile number and an accurate address are required. Food with the nearest expiry is prioritised.</p><form className="panel form-grid" onSubmit={submit}><Field label="Food type" name="foodType" onChange={change}/><Field label="Quantity" name="quantity" placeholder="e.g. 25 meals" onChange={change}/><Field label="Cooking time" type="datetime-local" name="cookingTime" onChange={change}/><Field label="Expiry time" type="datetime-local" name="expiryTime" onChange={change}/><Field label="10-digit mobile number" type="tel" name="phone" pattern="[6-9][0-9]{9}" onChange={change}/><label className="wide">Complete pickup address<textarea required minLength="12" name="address" onChange={change}/></label><label className="wide">Message for admin <textarea name="donorToAdminMsg" onChange={change}/></label><Error text={error}/><button className="primary">Submit verified donation</button></form></Page>}
function Donations({user,setNotice}){const{bucket}=useParams();const[data,setData]=useState();useEffect(()=>{setData();api(`/api/donations?bucket=${bucket}`).then(setData)},[bucket]);const cancel=async id=>{if(!confirm('Cancel this donation request?'))return;await api(`/api/donations/${id}`,{method:'DELETE'});setData({...data,donations:data.donations.filter(d=>d._id!==id)});setNotice({text:'Donation cancelled.'})};if(!data)return <Loading/>;return <Page title={bucket==='pending'?(user.role==='agent'?'Pickup queue':'Active donations'):(user.role==='agent'?'Collection history':'Donation history')}><p className="help-text">{user.role==='agent'&&bucket==='pending'?'Queue order: expiry emergency first, then nearest distance.':'Expired donations are automatically marked and cannot be collected.'}</p><div className="panel table-wrap"><table><thead><tr><th>Food</th><th>Quantity</th><th>Expiry / priority</th><th>Donor / pickup</th><th>Status</th><th></th></tr></thead><tbody>{data.donations.map(d=><tr key={d._id} className={d.hasExpired?'expired-row':''}><td>{d.foodType}</td><td>{d.quantity}</td><td><span className={'urgency '+String(d.urgency||'unknown').toLowerCase()}>{d.hasExpired?'Expired':d.urgency||'Standard'}</span><small>{d.expiryTime&&fmt(d.expiryTime)}</small>{Number.isFinite(d.distanceKm)&&d.distanceKm<1000000&&<small>{d.distanceKm.toFixed(1)} km away</small>}</td><td>{user.role==='agent'?d.address:(d.donor?.firstName+' '+d.donor?.lastName)}</td><td><span className={'status '+d.status}>{d.status}</span></td><td><Link className="text-link" to={`/${user.role}/donation/${d._id}`}>View</Link>{user.role==='donor'&&['pending','rejected'].includes(d.status)&&<button className="danger-text" onClick={()=>cancel(d._id)}>Cancel</button>}</td></tr>)}</tbody></table>{!data.donations.length&&<p>No records found.</p>}</div></Page>}
function DonationDetail({user,setNotice}){const{id}=useParams();const[data,setData]=useState();const[agents,setAgents]=useState([]);const[msg,setMsg]=useState('');useEffect(()=>{api(`/api/donations/${id}`).then(setData);if(user.role==='admin')api('/api/agents').then(r=>setAgents(r.agents))},[id]);const action=async (action, extra={})=>{try{const r=await api(`/api/donations/${id}/status`,{method:'PATCH',body:{action,...extra}});setData({donation:r.donation});setNotice({text:`Donation ${action}ed successfully.`})}catch(err){setNotice({type:'error',text:err.message})}};if(!data)return <Loading/>;const d=data.donation;return <Page title="Donation details"><section className="panel details"><div><b>Food type</b><span>{d.foodType}</span></div><div><b>Quantity</b><span>{d.quantity}</span></div><div><b>Cooked at</b><span>{fmt(d.cookingTime)}</span></div><div><b>Expires at</b><span>{d.expiryTime?fmt(d.expiryTime):'Not provided'}</span></div><div><b>Priority</b><span className={'urgency '+String(d.urgency||'unknown').toLowerCase()}>{d.hasExpired?'EXPIRED':d.urgency||'STANDARD'}</span></div><div><b>Pickup address</b><span>{d.address}</span></div><div><b>Phone</b><span>{d.phone}</span></div><div><b>Status</b><span className={'status '+d.status}>{d.status}</span></div>{d.donor&&<div><b>Donor</b><span>{d.donor.firstName} {d.donor.lastName}</span></div>}{d.agent&&<div><b>Assigned agent</b><span>{d.agent.firstName} {d.agent.lastName}</span></div>}</section>{user.role==='admin'&&!d.hasExpired&&<section className="actions panel"><button className="primary" onClick={()=>action('accept')}>Accept</button><button className="outline" onClick={()=>action('reject')}>Reject</button><select onChange={e=>e.target.value&&action('assign',{agent:e.target.value,adminToAgentMsg:msg})} defaultValue=""><option value="">Assign an agent…</option>{agents.map(a=><option value={a._id} key={a._id}>{a.firstName} {a.lastName}</option>)}</select><input placeholder="Message for agent (optional)" value={msg} onChange={e=>setMsg(e.target.value)}/></section>}{user.role==='agent'&&d.status==='assigned'&&!d.hasExpired&&<button className="primary" onClick={()=>action('collect')}>Mark as collected</button>}</Page>}
function RoutePlanner(){const[route,setRoute]=useState();const[error,setError]=useState('');useEffect(()=>{let cancelled=false;const load=async position=>{try{const q=position?`?lat=${position.coords.latitude}&lng=${position.coords.longitude}`:'';const plan=await api('/api/agent/route'+q);if(!cancelled)setRoute(plan)}catch(err){if(!cancelled)setError(err.message)}};navigator.geolocation?navigator.geolocation.getCurrentPosition(load,()=>load(null),{enableHighAccuracy:true,timeout:8000}):load(null);return()=>{cancelled=true}},[]);if(error)return <Page title="Route planner"><p className="error">{error}</p></Page>;if(!route)return <Loading/>;const center=route.origin||route.stops[0]?.location;const line=route.directions?.geometry?.coordinates?.map(([lng,lat])=>[lat,lng])||[];return <Page title="Priority route planner"><p className="help-text">OpenRouteService driving route: emergency expiry first, then nearest pickup distance. Your current location is used when permission is allowed.</p>{route.routingWarning&&<div className="panel map-note"><b>Route line unavailable</b><p>{route.routingWarning}. Stops and pickup order are still available below.</p></div>}{center&&<MapContainer center={[center.lat,center.lng]} zoom={12} className="route-map"><TileLayer attribution="© OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{line.length>1&&<Polyline positions={line} pathOptions={{color:'#166534',weight:5}}/>}<CircleMarker center={[center.lat,center.lng]} radius={9} pathOptions={{color:'#17211a',fillColor:'#fff',fillOpacity:1}}><Popup>Route start</Popup></CircleMarker>{route.stops.map(stop=>stop.location&&<CircleMarker key={stop._id} center={[stop.location.lat,stop.location.lng]} radius={10} pathOptions={{color:'#166534',fillColor:'#166534',fillOpacity:1}}><Popup>Stop {stop.pickupOrder}: {stop.foodType}<br/>{stop.address}</Popup></CircleMarker>)}</MapContainer>}<section className="panel route-stops">{route.directions?.summary&&<p className="route-summary">Driving distance: {(route.directions.summary.distance/1000).toFixed(1)} km · Estimated time: {Math.ceil(route.directions.summary.duration/60)} min</p>}{route.stops.map(stop=><article key={stop._id}><span className="stop-number">{stop.pickupOrder}</span><div><b>{stop.foodType} · {stop.quantity}</b><p>{stop.address}</p><small>{stop.urgency} · expires {fmt(stop.expiryTime)} {Number.isFinite(stop.distanceKm)&&stop.distanceKm<1000000?' · '+stop.distanceKm.toFixed(1)+' km':''}</small></div><Link className="text-link" to={'/agent/donation/'+stop._id}>View</Link></article>)}{!route.stops.length&&<p>No active pickup stops. Expired donations are excluded automatically.</p>}</section></Page>}
function Agents(){const[data,setData]=useState();useEffect(()=>api('/api/agents').then(setData),[]);if(!data)return <Loading/>;return <Page title="Collection agents"><div className="panel table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Address</th></tr></thead><tbody>{data.agents.map(a=><tr key={a._id}><td>{a.firstName} {a.lastName}</td><td>{a.email}</td><td>{a.phone||'—'}</td><td>{a.address||'—'}</td></tr>)}</tbody></table></div></Page>}
function Profile({user,setUser,setNotice}){const[v,change]=useForm(user);const save=async e=>{e.preventDefault();try{const r=await api('/api/profile',{method:'PATCH',body:v});setUser(r.user);setNotice({text:'Profile updated.'})}catch(err){setNotice({type:'error',text:err.message})}};const remove=async()=>{if(!confirm('Unregister your account? This cannot be undone.'))return;await api('/api/auth/account',{method:'DELETE'});setUser(null)};return <Page title="Your profile"><form className="panel form-grid" onSubmit={save}><div className="split wide"><Field label="First name" name="firstName" value={v.firstName||''} onChange={change}/><Field label="Last name" name="lastName" value={v.lastName||''} onChange={change}/></div><label>Email<input value={user.email} disabled/></label><label>Phone<input name="phone" value={v.phone||''} onChange={change}/></label><label>Gender<select name="gender" value={v.gender||''} onChange={change}><option value="">Prefer not to say</option><option value="male">Male</option><option value="female">Female</option></select></label><label className="wide">Address<textarea name="address" value={v.address||''} onChange={change}/></label><button className="primary">Save changes</button></form><button className="danger" onClick={remove}>Unregister account</button></Page>}
function Page({title:heading,children}){return <section className="page"><h1>{heading}</h1>{children}</section>} function Loading(){return <div className="loading">Loading…</div>}
function Faq({user}){const[open,setOpen]=useState(false),[question,setQuestion]=useState(''),[answer,setAnswer]=useState('');const ask=async e=>{e.preventDefault();if(!question.trim())return;try{setAnswer('Thinking…');const r=await api('/api/faq',{method:'POST',body:{question,role:user?.role||'guest'}});setAnswer(r.answer)}catch{setAnswer('I could not answer that right now.')}};return <div className="faq"><button className="faq-toggle" onClick={()=>setOpen(!open)}>?</button>{open&&<section><b>FoodConnect help</b><p>Ask about donations, pickups or account access.</p><form onSubmit={ask}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a question…"/><button>Ask</button></form>{answer&&<p className="answer">{answer}</p>}</section>}</div>}
createRoot(document.getElementById('root')).render(<BrowserRouter basename="/app"><App/></BrowserRouter>);
